// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: privacypolicy.proto

package cliwrapper

import edgeproto "github.com/mobiledgex/edge-cloud/edgeproto"
import "strings"
import "github.com/mobiledgex/edge-cloud-infra/mc/ormapi"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/googleapis/google/api"
import _ "github.com/mobiledgex/edge-cloud/protogen"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Auto-generated code: DO NOT EDIT

func (s *Client) CreatePrivacyPolicy(uri, token string, in *ormapi.RegionPrivacyPolicy) (edgeproto.Result, int, error) {
	args := []string{"region", "CreatePrivacyPolicy"}
	out := edgeproto.Result{}
	noconfig := strings.Split("", ",")
	st, err := s.runObjs(uri, token, args, in, &out, withIgnore(noconfig))
	return out, st, err
}

func (s *Client) DeletePrivacyPolicy(uri, token string, in *ormapi.RegionPrivacyPolicy) (edgeproto.Result, int, error) {
	args := []string{"region", "DeletePrivacyPolicy"}
	out := edgeproto.Result{}
	noconfig := strings.Split("", ",")
	st, err := s.runObjs(uri, token, args, in, &out, withIgnore(noconfig))
	return out, st, err
}

func (s *Client) UpdatePrivacyPolicy(uri, token string, in *ormapi.RegionPrivacyPolicy) (edgeproto.Result, int, error) {
	args := []string{"region", "UpdatePrivacyPolicy"}
	out := edgeproto.Result{}
	noconfig := strings.Split("", ",")
	st, err := s.runObjs(uri, token, args, in, &out, withIgnore(noconfig))
	return out, st, err
}

func (s *Client) ShowPrivacyPolicy(uri, token string, in *ormapi.RegionPrivacyPolicy) ([]edgeproto.PrivacyPolicy, int, error) {
	args := []string{"region", "ShowPrivacyPolicy"}
	outlist := []edgeproto.PrivacyPolicy{}
	noconfig := strings.Split("", ",")
	ops := []runOp{
		withIgnore(noconfig),
	}
	st, err := s.runObjs(uri, token, args, in, &outlist, ops...)
	return outlist, st, err
}
