// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: restagtable.proto

package cliwrapper

import (
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	"github.com/mobiledgex/edge-cloud-infra/mc/ormapi"
	edgeproto "github.com/mobiledgex/edge-cloud/edgeproto"
	_ "github.com/mobiledgex/edge-cloud/protogen"
	math "math"
	"strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Auto-generated code: DO NOT EDIT

func (s *Client) CreateResTagTable(uri, token string, in *ormapi.RegionResTagTable) (*edgeproto.Result, int, error) {
	args := []string{"region", "CreateResTagTable"}
	out := edgeproto.Result{}
	noconfig := strings.Split("", ",")
	st, err := s.runObjs(uri, token, args, in, &out, withIgnore(noconfig))
	if err != nil {
		return nil, st, err
	}
	return &out, st, err
}

func (s *Client) DeleteResTagTable(uri, token string, in *ormapi.RegionResTagTable) (*edgeproto.Result, int, error) {
	args := []string{"region", "DeleteResTagTable"}
	out := edgeproto.Result{}
	noconfig := strings.Split("", ",")
	st, err := s.runObjs(uri, token, args, in, &out, withIgnore(noconfig))
	if err != nil {
		return nil, st, err
	}
	return &out, st, err
}

func (s *Client) UpdateResTagTable(uri, token string, in *ormapi.RegionResTagTable) (*edgeproto.Result, int, error) {
	args := []string{"region", "UpdateResTagTable"}
	out := edgeproto.Result{}
	noconfig := strings.Split("", ",")
	st, err := s.runObjs(uri, token, args, in, &out, withIgnore(noconfig))
	if err != nil {
		return nil, st, err
	}
	return &out, st, err
}

func (s *Client) ShowResTagTable(uri, token string, in *ormapi.RegionResTagTable) ([]edgeproto.ResTagTable, int, error) {
	args := []string{"region", "ShowResTagTable"}
	outlist := []edgeproto.ResTagTable{}
	noconfig := strings.Split("", ",")
	ops := []runOp{
		withIgnore(noconfig),
	}
	st, err := s.runObjs(uri, token, args, in, &outlist, ops...)
	return outlist, st, err
}

func (s *Client) AddResTag(uri, token string, in *ormapi.RegionResTagTable) (*edgeproto.Result, int, error) {
	args := []string{"region", "AddResTag"}
	out := edgeproto.Result{}
	noconfig := strings.Split("", ",")
	st, err := s.runObjs(uri, token, args, in, &out, withIgnore(noconfig))
	if err != nil {
		return nil, st, err
	}
	return &out, st, err
}

func (s *Client) RemoveResTag(uri, token string, in *ormapi.RegionResTagTable) (*edgeproto.Result, int, error) {
	args := []string{"region", "RemoveResTag"}
	out := edgeproto.Result{}
	noconfig := strings.Split("", ",")
	st, err := s.runObjs(uri, token, args, in, &out, withIgnore(noconfig))
	if err != nil {
		return nil, st, err
	}
	return &out, st, err
}

func (s *Client) GetResTagTable(uri, token string, in *ormapi.RegionResTagTableKey) (*edgeproto.ResTagTable, int, error) {
	args := []string{"region", "GetResTagTable"}
	out := edgeproto.ResTagTable{}
	noconfig := strings.Split("", ",")
	st, err := s.runObjs(uri, token, args, in, &out, withIgnore(noconfig))
	if err != nil {
		return nil, st, err
	}
	return &out, st, err
}
