name 'setup_iptables_forwarding'
maintainer 'MobiledgeX Inc.'
maintainer_email 'mobiledgex.ops@mobiledgex.com'
description 'Creates iptable rules to setup routing to internet'
version '1.0.0'
chef_version '>= 14.0'
depends 'iptables'
