// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: app.proto

package ctrlapi

import (
	"context"
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	"github.com/mobiledgex/edge-cloud-infra/mc/ormutil"
	_ "github.com/mobiledgex/edge-cloud/d-match-engine/dme-proto"
	edgeproto "github.com/mobiledgex/edge-cloud/edgeproto"
	"github.com/mobiledgex/edge-cloud/log"
	_ "github.com/mobiledgex/edge-cloud/protogen"
	"google.golang.org/grpc"
	"io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Auto-generated code: DO NOT EDIT

func CreateAppObj(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.App, conn *grpc.ClientConn) (*edgeproto.Result, error) {
	span := log.SpanFromContext(ctx)
	span.SetTag("region", rc.Region)
	log.SetTags(span, obj.GetKey().GetTags())
	span.SetTag("org", obj.Key.Organization)
	log.SetContextTags(ctx, edgeproto.GetTags(obj))
	api := edgeproto.NewAppApiClient(conn)
	log.SpanLog(ctx, log.DebugLevelApi, "start controller api")
	defer log.SpanLog(ctx, log.DebugLevelApi, "finish controller api")
	return api.CreateApp(ctx, obj)
}

func DeleteAppObj(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.App, conn *grpc.ClientConn) (*edgeproto.Result, error) {
	span := log.SpanFromContext(ctx)
	span.SetTag("region", rc.Region)
	log.SetTags(span, obj.GetKey().GetTags())
	span.SetTag("org", obj.Key.Organization)
	log.SetContextTags(ctx, edgeproto.GetTags(obj))
	api := edgeproto.NewAppApiClient(conn)
	log.SpanLog(ctx, log.DebugLevelApi, "start controller api")
	defer log.SpanLog(ctx, log.DebugLevelApi, "finish controller api")
	return api.DeleteApp(ctx, obj)
}

func UpdateAppObj(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.App, conn *grpc.ClientConn) (*edgeproto.Result, error) {
	span := log.SpanFromContext(ctx)
	span.SetTag("region", rc.Region)
	log.SetTags(span, obj.GetKey().GetTags())
	span.SetTag("org", obj.Key.Organization)
	log.SetContextTags(ctx, edgeproto.GetTags(obj))
	api := edgeproto.NewAppApiClient(conn)
	log.SpanLog(ctx, log.DebugLevelApi, "start controller api")
	defer log.SpanLog(ctx, log.DebugLevelApi, "finish controller api")
	return api.UpdateApp(ctx, obj)
}

func ShowAppStream(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.App, conn *grpc.ClientConn, authzOk func(obj *edgeproto.App) (bool, bool), authzFilter func(obj *edgeproto.App), cb func(res *edgeproto.App) error) error {
	span := log.SpanFromContext(ctx)
	span.SetTag("region", rc.Region)
	log.SetTags(span, obj.GetKey().GetTags())
	span.SetTag("org", obj.Key.Organization)
	api := edgeproto.NewAppApiClient(conn)
	log.SpanLog(ctx, log.DebugLevelApi, "start controller api")
	defer log.SpanLog(ctx, log.DebugLevelApi, "finish controller api")
	stream, err := api.ShowApp(ctx, obj)
	if err != nil {
		return err
	}
	for {
		res, err := stream.Recv()
		if err == io.EOF {
			err = nil
			break
		}
		if err != nil {
			return err
		}
		if !rc.SkipAuthz {
			if authzOk != nil {
				isAuthzOk, filterOutput := authzOk(res)
				if !isAuthzOk {
					continue
				}
				if filterOutput && authzFilter != nil {
					authzFilter(res)
				}
			}
		}
		err = cb(res)
		if err != nil {
			return err
		}
	}
	return nil
}

func AddAppAutoProvPolicyObj(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.AppAutoProvPolicy, conn *grpc.ClientConn) (*edgeproto.Result, error) {
	span := log.SpanFromContext(ctx)
	span.SetTag("region", rc.Region)
	span.SetTag("org", obj.AppKey.Organization)
	log.SetContextTags(ctx, edgeproto.GetTags(obj))
	api := edgeproto.NewAppApiClient(conn)
	log.SpanLog(ctx, log.DebugLevelApi, "start controller api")
	defer log.SpanLog(ctx, log.DebugLevelApi, "finish controller api")
	return api.AddAppAutoProvPolicy(ctx, obj)
}

func RemoveAppAutoProvPolicyObj(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.AppAutoProvPolicy, conn *grpc.ClientConn) (*edgeproto.Result, error) {
	span := log.SpanFromContext(ctx)
	span.SetTag("region", rc.Region)
	span.SetTag("org", obj.AppKey.Organization)
	log.SetContextTags(ctx, edgeproto.GetTags(obj))
	api := edgeproto.NewAppApiClient(conn)
	log.SpanLog(ctx, log.DebugLevelApi, "start controller api")
	defer log.SpanLog(ctx, log.DebugLevelApi, "finish controller api")
	return api.RemoveAppAutoProvPolicy(ctx, obj)
}

func AddAppAlertPolicyObj(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.AppAlertPolicy, conn *grpc.ClientConn) (*edgeproto.Result, error) {
	span := log.SpanFromContext(ctx)
	span.SetTag("region", rc.Region)
	span.SetTag("org", obj.AppKey.Organization)
	log.SetContextTags(ctx, edgeproto.GetTags(obj))
	api := edgeproto.NewAppApiClient(conn)
	log.SpanLog(ctx, log.DebugLevelApi, "start controller api")
	defer log.SpanLog(ctx, log.DebugLevelApi, "finish controller api")
	return api.AddAppAlertPolicy(ctx, obj)
}

func RemoveAppAlertPolicyObj(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.AppAlertPolicy, conn *grpc.ClientConn) (*edgeproto.Result, error) {
	span := log.SpanFromContext(ctx)
	span.SetTag("region", rc.Region)
	span.SetTag("org", obj.AppKey.Organization)
	log.SetContextTags(ctx, edgeproto.GetTags(obj))
	api := edgeproto.NewAppApiClient(conn)
	log.SpanLog(ctx, log.DebugLevelApi, "start controller api")
	defer log.SpanLog(ctx, log.DebugLevelApi, "finish controller api")
	return api.RemoveAppAlertPolicy(ctx, obj)
}

func ShowCloudletsForAppDeploymentStream(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.DeploymentCloudletRequest, conn *grpc.ClientConn, authzOk func(obj *edgeproto.CloudletKey) (bool, bool), authzFilter func(obj *edgeproto.CloudletKey), cb func(res *edgeproto.CloudletKey) error) error {
	span := log.SpanFromContext(ctx)
	span.SetTag("region", rc.Region)
	api := edgeproto.NewAppApiClient(conn)
	log.SpanLog(ctx, log.DebugLevelApi, "start controller api")
	defer log.SpanLog(ctx, log.DebugLevelApi, "finish controller api")
	stream, err := api.ShowCloudletsForAppDeployment(ctx, obj)
	if err != nil {
		return err
	}
	for {
		res, err := stream.Recv()
		if err == io.EOF {
			err = nil
			break
		}
		if err != nil {
			return err
		}
		if !rc.SkipAuthz {
			if authzOk != nil {
				isAuthzOk, filterOutput := authzOk(res)
				if !isAuthzOk {
					continue
				}
				if filterOutput && authzFilter != nil {
					authzFilter(res)
				}
			}
		}
		err = cb(res)
		if err != nil {
			return err
		}
	}
	return nil
}
