// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cloudletpool.proto

package ctrlapi

import (
	"context"
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	"github.com/mobiledgex/edge-cloud-infra/mc/ormutil"
	_ "github.com/mobiledgex/edge-cloud/d-match-engine/dme-proto"
	edgeproto "github.com/mobiledgex/edge-cloud/edgeproto"
	"github.com/mobiledgex/edge-cloud/log"
	_ "github.com/mobiledgex/edge-cloud/protogen"
	"google.golang.org/grpc"
	"io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Auto-generated code: DO NOT EDIT

func CreateCloudletPoolObj(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.CloudletPool, conn *grpc.ClientConn) (*edgeproto.Result, error) {
	span := log.SpanFromContext(ctx)
	span.SetTag("region", rc.Region)
	log.SetTags(span, obj.GetKey().GetTags())
	span.SetTag("org", obj.Key.Organization)
	log.SetContextTags(ctx, edgeproto.GetTags(obj))
	api := edgeproto.NewCloudletPoolApiClient(conn)
	log.SpanLog(ctx, log.DebugLevelApi, "start controller api")
	defer log.SpanLog(ctx, log.DebugLevelApi, "finish controller api")
	return api.CreateCloudletPool(ctx, obj)
}

func DeleteCloudletPoolObj(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.CloudletPool, conn *grpc.ClientConn) (*edgeproto.Result, error) {
	span := log.SpanFromContext(ctx)
	span.SetTag("region", rc.Region)
	log.SetTags(span, obj.GetKey().GetTags())
	span.SetTag("org", obj.Key.Organization)
	log.SetContextTags(ctx, edgeproto.GetTags(obj))
	api := edgeproto.NewCloudletPoolApiClient(conn)
	log.SpanLog(ctx, log.DebugLevelApi, "start controller api")
	defer log.SpanLog(ctx, log.DebugLevelApi, "finish controller api")
	return api.DeleteCloudletPool(ctx, obj)
}

func UpdateCloudletPoolObj(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.CloudletPool, conn *grpc.ClientConn) (*edgeproto.Result, error) {
	span := log.SpanFromContext(ctx)
	span.SetTag("region", rc.Region)
	log.SetTags(span, obj.GetKey().GetTags())
	span.SetTag("org", obj.Key.Organization)
	log.SetContextTags(ctx, edgeproto.GetTags(obj))
	api := edgeproto.NewCloudletPoolApiClient(conn)
	log.SpanLog(ctx, log.DebugLevelApi, "start controller api")
	defer log.SpanLog(ctx, log.DebugLevelApi, "finish controller api")
	return api.UpdateCloudletPool(ctx, obj)
}

func ShowCloudletPoolStream(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.CloudletPool, conn *grpc.ClientConn, authzOk func(org string) bool, cb func(res *edgeproto.CloudletPool) error) error {
	span := log.SpanFromContext(ctx)
	span.SetTag("region", rc.Region)
	log.SetTags(span, obj.GetKey().GetTags())
	span.SetTag("org", obj.Key.Organization)
	api := edgeproto.NewCloudletPoolApiClient(conn)
	log.SpanLog(ctx, log.DebugLevelApi, "start controller api")
	defer log.SpanLog(ctx, log.DebugLevelApi, "finish controller api")
	stream, err := api.ShowCloudletPool(ctx, obj)
	if err != nil {
		return err
	}
	for {
		res, err := stream.Recv()
		if err == io.EOF {
			err = nil
			break
		}
		if err != nil {
			return err
		}
		if !rc.SkipAuthz {
			if authzOk != nil {
				if !authzOk(res.Key.Organization) {
					continue
				}
			}
		}
		err = cb(res)
		if err != nil {
			return err
		}
	}
	return nil
}

func AddCloudletPoolMemberObj(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.CloudletPoolMember, conn *grpc.ClientConn) (*edgeproto.Result, error) {
	span := log.SpanFromContext(ctx)
	span.SetTag("region", rc.Region)
	log.SetTags(span, obj.GetKey().GetTags())
	span.SetTag("org", obj.Key.Organization)
	log.SetContextTags(ctx, edgeproto.GetTags(obj))
	api := edgeproto.NewCloudletPoolApiClient(conn)
	log.SpanLog(ctx, log.DebugLevelApi, "start controller api")
	defer log.SpanLog(ctx, log.DebugLevelApi, "finish controller api")
	return api.AddCloudletPoolMember(ctx, obj)
}

func RemoveCloudletPoolMemberObj(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.CloudletPoolMember, conn *grpc.ClientConn) (*edgeproto.Result, error) {
	span := log.SpanFromContext(ctx)
	span.SetTag("region", rc.Region)
	log.SetTags(span, obj.GetKey().GetTags())
	span.SetTag("org", obj.Key.Organization)
	log.SetContextTags(ctx, edgeproto.GetTags(obj))
	api := edgeproto.NewCloudletPoolApiClient(conn)
	log.SpanLog(ctx, log.DebugLevelApi, "start controller api")
	defer log.SpanLog(ctx, log.DebugLevelApi, "finish controller api")
	return api.RemoveCloudletPoolMember(ctx, obj)
}
