// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: trustpolicy.proto

package ctrlapi

import (
	"context"
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	"github.com/mobiledgex/edge-cloud-infra/mc/ormutil"
	edgeproto "github.com/mobiledgex/edge-cloud/edgeproto"
	"github.com/mobiledgex/edge-cloud/log"
	_ "github.com/mobiledgex/edge-cloud/protogen"
	"google.golang.org/grpc"
	"io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Auto-generated code: DO NOT EDIT

func CreateTrustPolicyStream(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.TrustPolicy, conn *grpc.ClientConn, cb func(res *edgeproto.Result) error) error {
	span := log.SpanFromContext(ctx)
	span.SetTag("region", rc.Region)
	log.SetTags(span, obj.GetKey().GetTags())
	span.SetTag("org", obj.Key.Organization)
	log.SetContextTags(ctx, edgeproto.GetTags(obj))
	api := edgeproto.NewTrustPolicyApiClient(conn)
	log.SpanLog(ctx, log.DebugLevelApi, "start controller api")
	defer log.SpanLog(ctx, log.DebugLevelApi, "finish controller api")
	stream, err := api.CreateTrustPolicy(ctx, obj)
	if err != nil {
		return err
	}
	for {
		res, err := stream.Recv()
		if err == io.EOF {
			err = nil
			break
		}
		if err != nil {
			return err
		}
		err = cb(res)
		if err != nil {
			return err
		}
	}
	return nil
}

func DeleteTrustPolicyStream(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.TrustPolicy, conn *grpc.ClientConn, cb func(res *edgeproto.Result) error) error {
	span := log.SpanFromContext(ctx)
	span.SetTag("region", rc.Region)
	log.SetTags(span, obj.GetKey().GetTags())
	span.SetTag("org", obj.Key.Organization)
	log.SetContextTags(ctx, edgeproto.GetTags(obj))
	api := edgeproto.NewTrustPolicyApiClient(conn)
	log.SpanLog(ctx, log.DebugLevelApi, "start controller api")
	defer log.SpanLog(ctx, log.DebugLevelApi, "finish controller api")
	stream, err := api.DeleteTrustPolicy(ctx, obj)
	if err != nil {
		return err
	}
	for {
		res, err := stream.Recv()
		if err == io.EOF {
			err = nil
			break
		}
		if err != nil {
			return err
		}
		err = cb(res)
		if err != nil {
			return err
		}
	}
	return nil
}

func UpdateTrustPolicyStream(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.TrustPolicy, conn *grpc.ClientConn, cb func(res *edgeproto.Result) error) error {
	span := log.SpanFromContext(ctx)
	span.SetTag("region", rc.Region)
	log.SetTags(span, obj.GetKey().GetTags())
	span.SetTag("org", obj.Key.Organization)
	log.SetContextTags(ctx, edgeproto.GetTags(obj))
	api := edgeproto.NewTrustPolicyApiClient(conn)
	log.SpanLog(ctx, log.DebugLevelApi, "start controller api")
	defer log.SpanLog(ctx, log.DebugLevelApi, "finish controller api")
	stream, err := api.UpdateTrustPolicy(ctx, obj)
	if err != nil {
		return err
	}
	for {
		res, err := stream.Recv()
		if err == io.EOF {
			err = nil
			break
		}
		if err != nil {
			return err
		}
		err = cb(res)
		if err != nil {
			return err
		}
	}
	return nil
}

func ShowTrustPolicyStream(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.TrustPolicy, conn *grpc.ClientConn, authzOk func(obj *edgeproto.TrustPolicy) (bool, bool), authzFilter func(obj *edgeproto.TrustPolicy), cb func(res *edgeproto.TrustPolicy) error) error {
	span := log.SpanFromContext(ctx)
	span.SetTag("region", rc.Region)
	log.SetTags(span, obj.GetKey().GetTags())
	span.SetTag("org", obj.Key.Organization)
	api := edgeproto.NewTrustPolicyApiClient(conn)
	log.SpanLog(ctx, log.DebugLevelApi, "start controller api")
	defer log.SpanLog(ctx, log.DebugLevelApi, "finish controller api")
	stream, err := api.ShowTrustPolicy(ctx, obj)
	if err != nil {
		return err
	}
	for {
		res, err := stream.Recv()
		if err == io.EOF {
			err = nil
			break
		}
		if err != nil {
			return err
		}
		if !rc.SkipAuthz {
			if authzOk != nil {
				isAuthzOk, filterOutput := authzOk(res)
				if !isAuthzOk {
					continue
				}
				if filterOutput && authzFilter != nil {
					authzFilter(res)
				}
			}
		}
		err = cb(res)
		if err != nil {
			return err
		}
	}
	return nil
}
