name 'setup_services'
maintainer 'MobiledgeX Inc.'
maintainer_email 'mobiledgex.ops@mobiledgex.com'
description 'Setup services on docker/k8s containers'
version '0.0.1'
chef_version '>= 14.0'
depends 'docker'
