// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: flavor.proto

package ormctl

import (
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	"github.com/mobiledgex/edge-cloud-infra/mc/ormapi"
	"github.com/mobiledgex/edge-cloud/cli"
	edgeproto "github.com/mobiledgex/edge-cloud/edgeproto"
	_ "github.com/mobiledgex/edge-cloud/protogen"
	math "math"
	"strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Auto-generated code: DO NOT EDIT

var CreateFlavorCmd = &ApiCommand{
	Name:         "CreateFlavor",
	Use:          "create",
	Short:        "Create a Flavor",
	RequiredArgs: "region " + strings.Join(CreateFlavorRequiredArgs, " "),
	OptionalArgs: strings.Join(CreateFlavorOptionalArgs, " "),
	AliasArgs:    strings.Join(FlavorAliasArgs, " "),
	SpecialArgs:  &FlavorSpecialArgs,
	Comments:     addRegionComment(FlavorComments),
	ReqData:      &ormapi.RegionFlavor{},
	ReplyData:    &edgeproto.Result{},
	Path:         "/auth/ctrl/CreateFlavor",
	ProtobufApi:  true,
}

var DeleteFlavorCmd = &ApiCommand{
	Name:         "DeleteFlavor",
	Use:          "delete",
	Short:        "Delete a Flavor",
	RequiredArgs: "region " + strings.Join(FlavorRequiredArgs, " "),
	OptionalArgs: strings.Join(FlavorOptionalArgs, " "),
	AliasArgs:    strings.Join(FlavorAliasArgs, " "),
	SpecialArgs:  &FlavorSpecialArgs,
	Comments:     addRegionComment(FlavorComments),
	ReqData:      &ormapi.RegionFlavor{},
	ReplyData:    &edgeproto.Result{},
	Path:         "/auth/ctrl/DeleteFlavor",
	ProtobufApi:  true,
}

var UpdateFlavorCmd = &ApiCommand{
	Name:          "UpdateFlavor",
	Use:           "update",
	Short:         "Update a Flavor",
	RequiredArgs:  "region " + strings.Join(FlavorRequiredArgs, " "),
	OptionalArgs:  strings.Join(FlavorOptionalArgs, " "),
	AliasArgs:     strings.Join(FlavorAliasArgs, " "),
	SpecialArgs:   &FlavorSpecialArgs,
	Comments:      addRegionComment(FlavorComments),
	ReqData:       &ormapi.RegionFlavor{},
	ReplyData:     &edgeproto.Result{},
	Path:          "/auth/ctrl/UpdateFlavor",
	SetFieldsFunc: SetUpdateFlavorFields,
	ProtobufApi:   true,
}

func SetUpdateFlavorFields(in map[string]interface{}) {
	// get map for edgeproto object in region struct
	obj := in["Flavor"]
	if obj == nil {
		return
	}
	objmap, ok := obj.(map[string]interface{})
	if !ok {
		return
	}
	fields := cli.GetSpecifiedFields(objmap, &edgeproto.Flavor{}, cli.JsonNamespace)
	// include fields already specified
	if inFields, found := objmap["fields"]; found {
		if fieldsArr, ok := inFields.([]string); ok {
			fields = append(fields, fieldsArr...)
		}
	}
	objmap["fields"] = fields
}

var ShowFlavorCmd = &ApiCommand{
	Name:         "ShowFlavor",
	Use:          "show",
	Short:        "Show Flavors",
	RequiredArgs: "region",
	OptionalArgs: strings.Join(append(FlavorRequiredArgs, FlavorOptionalArgs...), " "),
	AliasArgs:    strings.Join(FlavorAliasArgs, " "),
	SpecialArgs:  &FlavorSpecialArgs,
	Comments:     addRegionComment(FlavorComments),
	ReqData:      &ormapi.RegionFlavor{},
	ReplyData:    &edgeproto.Flavor{},
	Path:         "/auth/ctrl/ShowFlavor",
	StreamOut:    true,
	ProtobufApi:  true,
}

var AddFlavorResCmd = &ApiCommand{
	Name:         "AddFlavorRes",
	Use:          "addres",
	Short:        "Add Optional Resource",
	RequiredArgs: "region " + strings.Join(FlavorRequiredArgs, " "),
	OptionalArgs: strings.Join(FlavorOptionalArgs, " "),
	AliasArgs:    strings.Join(FlavorAliasArgs, " "),
	SpecialArgs:  &FlavorSpecialArgs,
	Comments:     addRegionComment(FlavorComments),
	ReqData:      &ormapi.RegionFlavor{},
	ReplyData:    &edgeproto.Result{},
	Path:         "/auth/ctrl/AddFlavorRes",
	ProtobufApi:  true,
}

var RemoveFlavorResCmd = &ApiCommand{
	Name:         "RemoveFlavorRes",
	Use:          "removeres",
	Short:        "Remove Optional Resource",
	RequiredArgs: "region " + strings.Join(FlavorRequiredArgs, " "),
	OptionalArgs: strings.Join(FlavorOptionalArgs, " "),
	AliasArgs:    strings.Join(FlavorAliasArgs, " "),
	SpecialArgs:  &FlavorSpecialArgs,
	Comments:     addRegionComment(FlavorComments),
	ReqData:      &ormapi.RegionFlavor{},
	ReplyData:    &edgeproto.Result{},
	Path:         "/auth/ctrl/RemoveFlavorRes",
	ProtobufApi:  true,
}

var FlavorApiCmds = []*ApiCommand{
	CreateFlavorCmd,
	DeleteFlavorCmd,
	UpdateFlavorCmd,
	ShowFlavorCmd,
	AddFlavorResCmd,
	RemoveFlavorResCmd,
}

const FlavorGroup = "Flavor"

func init() {
	AllApis.AddGroup(FlavorGroup, "Manage Flavors", FlavorApiCmds)
}

var CreateFlavorRequiredArgs = []string{
	"name",
	"ram",
	"vcpus",
	"disk",
}
var CreateFlavorOptionalArgs = []string{
	"optresmap",
}
var FlavorKeyRequiredArgs = []string{}
var FlavorKeyOptionalArgs = []string{
	"name",
}
var FlavorKeyAliasArgs = []string{
	"name=flavorkey.name",
}
var FlavorKeyComments = map[string]string{
	"name": "Flavor name",
}
var FlavorKeySpecialArgs = map[string]string{}
var FlavorRequiredArgs = []string{
	"name",
}
var FlavorOptionalArgs = []string{
	"ram",
	"vcpus",
	"disk",
	"optresmap",
}
var FlavorAliasArgs = []string{
	"fields=flavor.fields",
	"name=flavor.key.name",
	"ram=flavor.ram",
	"vcpus=flavor.vcpus",
	"disk=flavor.disk",
	"optresmap=flavor.optresmap",
}
var FlavorComments = map[string]string{
	"fields":    "Fields are used for the Update API to specify which fields to apply",
	"name":      "Flavor name",
	"ram":       "RAM in megabytes",
	"vcpus":     "Number of virtual CPUs",
	"disk":      "Amount of disk space in gigabytes",
	"optresmap": "Optional Resources request, key = gpu form: $resource=$kind:[$alias]$count ex: optresmap=gpu=vgpu:nvidia-63:1",
}
var FlavorSpecialArgs = map[string]string{
	"flavor.fields":    "StringArray",
	"flavor.optresmap": "StringToString",
}
