// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: flavor.proto

package ormctl

import edgeproto "github.com/mobiledgex/edge-cloud/edgeproto"
import "github.com/mobiledgex/edge-cloud-infra/mc/ormapi"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/googleapis/google/api"
import _ "github.com/mobiledgex/edge-cloud/protogen"
import _ "github.com/mobiledgex/edge-cloud/protoc-gen-cmd/protocmd"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Auto-generated code: DO NOT EDIT

var CreateFlavorCmd = &Command{
	Use:          "CreateFlavor",
	ReqData:      &ormapi.RegionFlavor{},
	ReplyData:    &edgeproto.Result{},
	Path:         "/auth/ctrl/CreateFlavor",
	OptionalArgs: "region",
}

var DeleteFlavorCmd = &Command{
	Use:          "DeleteFlavor",
	ReqData:      &ormapi.RegionFlavor{},
	ReplyData:    &edgeproto.Result{},
	Path:         "/auth/ctrl/DeleteFlavor",
	OptionalArgs: "region",
}

var UpdateFlavorCmd = &Command{
	Use:          "UpdateFlavor",
	ReqData:      &ormapi.RegionFlavor{},
	ReplyData:    &edgeproto.Result{},
	Path:         "/auth/ctrl/UpdateFlavor",
	OptionalArgs: "region",
}

var ShowFlavorCmd = &Command{
	Use:          "ShowFlavor",
	ReqData:      &ormapi.RegionFlavor{},
	ReplyData:    &edgeproto.Flavor{},
	Path:         "/auth/ctrl/ShowFlavor",
	OptionalArgs: "region",
	StreamOut:    true,
}
var FlavorApiCmds = []*Command{
	CreateFlavorCmd,
	DeleteFlavorCmd,
	UpdateFlavorCmd,
	ShowFlavorCmd,
}
