// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: operatorcode.proto

package ormctl

import (
	fmt "fmt"
	"github.com/edgexr/edge-cloud-infra/mc/ormapi"
	edgeproto "github.com/edgexr/edge-cloud/edgeproto"
	_ "github.com/edgexr/edge-cloud/protogen"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
	"strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Auto-generated code: DO NOT EDIT

var CreateOperatorCodeCmd = &ApiCommand{
	Name:         "CreateOperatorCode",
	Use:          "create",
	Short:        "Create Operator Code. Create a code for an Operator.",
	RequiredArgs: "region " + strings.Join(OperatorCodeRequiredArgs, " "),
	OptionalArgs: strings.Join(OperatorCodeOptionalArgs, " "),
	AliasArgs:    strings.Join(OperatorCodeAliasArgs, " "),
	SpecialArgs:  &OperatorCodeSpecialArgs,
	Comments:     addRegionComment(OperatorCodeComments),
	ReqData:      &ormapi.RegionOperatorCode{},
	ReplyData:    &edgeproto.Result{},
	Path:         "/auth/ctrl/CreateOperatorCode",
	ProtobufApi:  true,
}

var DeleteOperatorCodeCmd = &ApiCommand{
	Name:         "DeleteOperatorCode",
	Use:          "delete",
	Short:        "Delete Operator Code. Delete a code for an Operator.",
	RequiredArgs: "region " + strings.Join(OperatorCodeRequiredArgs, " "),
	OptionalArgs: strings.Join(OperatorCodeOptionalArgs, " "),
	AliasArgs:    strings.Join(OperatorCodeAliasArgs, " "),
	SpecialArgs:  &OperatorCodeSpecialArgs,
	Comments:     addRegionComment(OperatorCodeComments),
	ReqData:      &ormapi.RegionOperatorCode{},
	ReplyData:    &edgeproto.Result{},
	Path:         "/auth/ctrl/DeleteOperatorCode",
	ProtobufApi:  true,
}

var ShowOperatorCodeCmd = &ApiCommand{
	Name:         "ShowOperatorCode",
	Use:          "show",
	Short:        "Show Operator Code. Show Codes for an Operator.",
	RequiredArgs: "region",
	OptionalArgs: strings.Join(append(OperatorCodeRequiredArgs, OperatorCodeOptionalArgs...), " "),
	AliasArgs:    strings.Join(OperatorCodeAliasArgs, " "),
	SpecialArgs:  &OperatorCodeSpecialArgs,
	Comments:     addRegionComment(OperatorCodeComments),
	ReqData:      &ormapi.RegionOperatorCode{},
	ReplyData:    &edgeproto.OperatorCode{},
	Path:         "/auth/ctrl/ShowOperatorCode",
	StreamOut:    true,
	ProtobufApi:  true,
}
var OperatorCodeApiCmds = []*ApiCommand{
	CreateOperatorCodeCmd,
	DeleteOperatorCodeCmd,
	ShowOperatorCodeCmd,
}

const OperatorCodeGroup = "OperatorCode"

func init() {
	AllApis.AddGroup(OperatorCodeGroup, "Manage OperatorCodes", OperatorCodeApiCmds)
}

var OperatorCodeRequiredArgs = []string{}
var OperatorCodeOptionalArgs = []string{
	"code",
	"organization",
}
var OperatorCodeAliasArgs = []string{
	"code=operatorcode.code",
	"organization=operatorcode.organization",
}
var OperatorCodeComments = map[string]string{
	"code":         "MCC plus MNC code, or custom carrier code designation.",
	"organization": "Operator Organization name",
}
var OperatorCodeSpecialArgs = map[string]string{}
