// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: settings.proto

package ormctl

import (
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	"github.com/mobiledgex/edge-cloud-infra/mc/ormapi"
	"github.com/mobiledgex/edge-cloud/cli"
	edgeproto "github.com/mobiledgex/edge-cloud/edgeproto"
	_ "github.com/mobiledgex/edge-cloud/protogen"
	math "math"
	"strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Auto-generated code: DO NOT EDIT

var UpdateSettingsCmd = &cli.Command{
	Use:          "update",
	Short:        "Update settings",
	RequiredArgs: "region " + strings.Join(SettingsRequiredArgs, " "),
	OptionalArgs: strings.Join(SettingsOptionalArgs, " "),
	AliasArgs:    strings.Join(SettingsAliasArgs, " "),
	SpecialArgs:  &SettingsSpecialArgs,
	Comments:     addRegionComment(SettingsComments),
	ReqData:      &ormapi.RegionSettings{},
	ReplyData:    &edgeproto.Result{},
	Run: runRest("/auth/ctrl/UpdateSettings",
		withSetFieldsFunc(setUpdateSettingsFields),
	),
}

func setUpdateSettingsFields(in map[string]interface{}) {
	// get map for edgeproto object in region struct
	obj := in[strings.ToLower("Settings")]
	if obj == nil {
		return
	}
	objmap, ok := obj.(map[string]interface{})
	if !ok {
		return
	}
	fields := cli.GetSpecifiedFields(objmap, &edgeproto.Settings{}, cli.JsonNamespace)
	// include fields already specified
	if inFields, found := objmap["fields"]; found {
		if fieldsArr, ok := inFields.([]string); ok {
			fields = append(fields, fieldsArr...)
		}
	}
	objmap["fields"] = fields
}

var ResetSettingsCmd = &cli.Command{
	Use:          "reset",
	Short:        "Reset all settings to their defaults",
	RequiredArgs: "region " + strings.Join(SettingsRequiredArgs, " "),
	OptionalArgs: strings.Join(SettingsOptionalArgs, " "),
	AliasArgs:    strings.Join(SettingsAliasArgs, " "),
	SpecialArgs:  &SettingsSpecialArgs,
	Comments:     addRegionComment(SettingsComments),
	ReqData:      &ormapi.RegionSettings{},
	ReplyData:    &edgeproto.Result{},
	Run:          runRest("/auth/ctrl/ResetSettings"),
}

var ShowSettingsCmd = &cli.Command{
	Use:          "show",
	Short:        "Show settings",
	RequiredArgs: "region " + strings.Join(SettingsRequiredArgs, " "),
	OptionalArgs: strings.Join(SettingsOptionalArgs, " "),
	AliasArgs:    strings.Join(SettingsAliasArgs, " "),
	SpecialArgs:  &SettingsSpecialArgs,
	Comments:     addRegionComment(SettingsComments),
	ReqData:      &ormapi.RegionSettings{},
	ReplyData:    &edgeproto.Settings{},
	Run:          runRest("/auth/ctrl/ShowSettings"),
}

var SettingsApiCmds = []*cli.Command{
	UpdateSettingsCmd,
	ResetSettingsCmd,
	ShowSettingsCmd,
}

var SettingsApiCmdsGroup = cli.GenGroup("settings", "Manage Settings", SettingsApiCmds)

var SettingsRequiredArgs = []string{}
var SettingsOptionalArgs = []string{
	"shepherdmetricscollectioninterval",
	"shepherdalertevaluationinterval",
	"shepherdhealthcheckretries",
	"shepherdhealthcheckinterval",
	"autodeployintervalsec",
	"autodeployoffsetsec",
	"autodeploymaxintervals",
	"createappinsttimeout",
	"updateappinsttimeout",
	"deleteappinsttimeout",
	"createclusterinsttimeout",
	"updateclusterinsttimeout",
	"deleteclusterinsttimeout",
	"masternodeflavor",
	"maxtrackeddmeclients",
	"chefclientinterval",
	"influxdbmetricsretention",
	"cloudletmaintenancetimeout",
	"updatevmpooltimeout",
	"updatetrustpolicytimeout",
	"dmeapimetricscollectioninterval",
	"edgeeventsmetricscollectioninterval",
	"cleanupreservableautoclusteridletime",
	"influxdbcloudletusagemetricsretention",
	"createcloudlettimeout",
	"updatecloudlettimeout",
	"locationtilesidelengthkm",
	"edgeeventsmetricscontinuousqueriescollectionintervals:#.interval",
	"influxdbdownsampledmetricsretention",
	"influxdbedgeeventsmetricsretention",
	"appinstclientcleanupinterval",
}
var SettingsAliasArgs = []string{
	"fields=settings.fields",
	"shepherdmetricscollectioninterval=settings.shepherdmetricscollectioninterval",
	"shepherdalertevaluationinterval=settings.shepherdalertevaluationinterval",
	"shepherdhealthcheckretries=settings.shepherdhealthcheckretries",
	"shepherdhealthcheckinterval=settings.shepherdhealthcheckinterval",
	"autodeployintervalsec=settings.autodeployintervalsec",
	"autodeployoffsetsec=settings.autodeployoffsetsec",
	"autodeploymaxintervals=settings.autodeploymaxintervals",
	"createappinsttimeout=settings.createappinsttimeout",
	"updateappinsttimeout=settings.updateappinsttimeout",
	"deleteappinsttimeout=settings.deleteappinsttimeout",
	"createclusterinsttimeout=settings.createclusterinsttimeout",
	"updateclusterinsttimeout=settings.updateclusterinsttimeout",
	"deleteclusterinsttimeout=settings.deleteclusterinsttimeout",
	"masternodeflavor=settings.masternodeflavor",
	"maxtrackeddmeclients=settings.maxtrackeddmeclients",
	"chefclientinterval=settings.chefclientinterval",
	"influxdbmetricsretention=settings.influxdbmetricsretention",
	"cloudletmaintenancetimeout=settings.cloudletmaintenancetimeout",
	"updatevmpooltimeout=settings.updatevmpooltimeout",
	"updatetrustpolicytimeout=settings.updatetrustpolicytimeout",
	"dmeapimetricscollectioninterval=settings.dmeapimetricscollectioninterval",
	"edgeeventsmetricscollectioninterval=settings.edgeeventsmetricscollectioninterval",
	"cleanupreservableautoclusteridletime=settings.cleanupreservableautoclusteridletime",
	"influxdbcloudletusagemetricsretention=settings.influxdbcloudletusagemetricsretention",
	"createcloudlettimeout=settings.createcloudlettimeout",
	"updatecloudlettimeout=settings.updatecloudlettimeout",
	"locationtilesidelengthkm=settings.locationtilesidelengthkm",
	"edgeeventsmetricscontinuousqueriescollectionintervals:#.interval=settings.edgeeventsmetricscontinuousqueriescollectionintervals:#.interval",
	"influxdbdownsampledmetricsretention=settings.influxdbdownsampledmetricsretention",
	"influxdbedgeeventsmetricsretention=settings.influxdbedgeeventsmetricsretention",
	"appinstclientcleanupinterval=settings.appinstclientcleanupinterval",
}
var SettingsComments = map[string]string{
	"fields":                                "Fields are used for the Update API to specify which fields to apply",
	"shepherdmetricscollectioninterval":     "Shepherd metrics collection interval for k8s and docker appInstances (duration)",
	"shepherdalertevaluationinterval":       "Shepherd alert evaluation interval for k8s and docker appInstances (duration)",
	"shepherdhealthcheckretries":            "Number of times Shepherd Health Check fails before we mark appInst down",
	"shepherdhealthcheckinterval":           "Health Checking probing frequency (duration)",
	"autodeployintervalsec":                 "Auto Provisioning Stats push and analysis interval (seconds)",
	"autodeployoffsetsec":                   "Auto Provisioning analysis offset from interval (seconds)",
	"autodeploymaxintervals":                "Auto Provisioning Policy max allowed intervals",
	"createappinsttimeout":                  "Create AppInst timeout (duration)",
	"updateappinsttimeout":                  "Update AppInst timeout (duration)",
	"deleteappinsttimeout":                  "Delete AppInst timeout (duration)",
	"createclusterinsttimeout":              "Create ClusterInst timeout (duration)",
	"updateclusterinsttimeout":              "Update ClusterInst timeout (duration)",
	"deleteclusterinsttimeout":              "Delete ClusterInst timeout (duration)",
	"masternodeflavor":                      "Default flavor for k8s master VM and > 0  workers",
	"maxtrackeddmeclients":                  "Max DME clients to be tracked at the same time.",
	"chefclientinterval":                    "Default chef client interval (duration)",
	"influxdbmetricsretention":              "Default influxDB metrics retention policy (duration)",
	"cloudletmaintenancetimeout":            "Default Cloudlet Maintenance timeout (used twice for AutoProv and Cloudlet)",
	"updatevmpooltimeout":                   "Update VM pool timeout (duration)",
	"updatetrustpolicytimeout":              "Update Trust Policy timeout (duration)",
	"dmeapimetricscollectioninterval":       "Metrics collection interval for DME API counts (duration)",
	"edgeeventsmetricscollectioninterval":   "Collection interval for edgeevents metrics (latency, device, and custom)",
	"cleanupreservableautoclusteridletime":  "Idle reservable ClusterInst clean up time",
	"influxdbcloudletusagemetricsretention": "Default influxDB cloudlet usage metrics retention policy (duration)",
	"createcloudlettimeout":                 "Create Cloudlet timeout (duration)",
	"updatecloudlettimeout":                 "Update Cloudlet timeout (duration)",
	"locationtilesidelengthkm":              "Length of location tiles side for latency metrics (km)",
	"influxdbdownsampledmetricsretention":   "Default retention policy for downsampled influx db (duration)",
	"influxdbedgeeventsmetricsretention":    "Default retention policy for edgeevents metrics influx db (duration)",
	"appinstclientcleanupinterval":          "AppInstClient cleanup thread run interval",
}
var SettingsSpecialArgs = map[string]string{
	"settings.fields": "StringArray",
}
var CollectionIntervalRequiredArgs = []string{}
var CollectionIntervalOptionalArgs = []string{
	"interval",
}
var CollectionIntervalAliasArgs = []string{
	"interval=collectioninterval.interval",
}
var CollectionIntervalComments = map[string]string{}
var CollectionIntervalSpecialArgs = map[string]string{}
