name 'disable_password_expiry'
maintainer 'MobiledgeX Inc.'
maintainer_email 'mobiledgex.ops@mobiledgex.com'
description 'Disable password expiry for the ubuntu user'
version '1.0.0'
chef_version '>= 14.0'
