// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: appinst.proto

package ormapi

import (
	fmt "fmt"
	_ "github.com/edgexr/edge-cloud/d-match-engine/dme-proto"
	edgeproto "github.com/edgexr/edge-cloud/edgeproto"
	_ "github.com/edgexr/edge-cloud/protogen"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Auto-generated code: DO NOT EDIT

// Request summary for CreateAppInst
// swagger:parameters CreateAppInst
type swaggerCreateAppInst struct {
	// in: body
	Body RegionAppInst
}

type RegionAppInst struct {
	// Region name
	// required: true
	Region string
	// AppInst in region
	AppInst edgeproto.AppInst
}

func (s *RegionAppInst) GetRegion() string {
	return s.Region
}

func (s *RegionAppInst) GetObj() interface{} {
	return &s.AppInst
}

func (s *RegionAppInst) GetObjName() string {
	return "AppInst"
}
func (s *RegionAppInst) GetObjFields() []string {
	return s.AppInst.Fields
}

func (s *RegionAppInst) SetObjFields(fields []string) {
	s.AppInst.Fields = fields
}

// Request summary for DeleteAppInst
// swagger:parameters DeleteAppInst
type swaggerDeleteAppInst struct {
	// in: body
	Body RegionAppInst
}

// Request summary for RefreshAppInst
// swagger:parameters RefreshAppInst
type swaggerRefreshAppInst struct {
	// in: body
	Body RegionAppInst
}

// Request summary for UpdateAppInst
// swagger:parameters UpdateAppInst
type swaggerUpdateAppInst struct {
	// in: body
	Body RegionAppInst
}

// Request summary for ShowAppInst
// swagger:parameters ShowAppInst
type swaggerShowAppInst struct {
	// in: body
	Body RegionAppInst
}

// Request summary for RequestAppInstLatency
// swagger:parameters RequestAppInstLatency
type swaggerRequestAppInstLatency struct {
	// in: body
	Body RegionAppInstLatency
}

type RegionAppInstLatency struct {
	// Region name
	// required: true
	Region string
	// AppInstLatency in region
	AppInstLatency edgeproto.AppInstLatency
}

func (s *RegionAppInstLatency) GetRegion() string {
	return s.Region
}

func (s *RegionAppInstLatency) GetObj() interface{} {
	return &s.AppInstLatency
}

func (s *RegionAppInstLatency) GetObjName() string {
	return "AppInstLatency"
}
