// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: node.proto

package ormapi

import (
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	edgeproto "github.com/mobiledgex/edge-cloud/edgeproto"
	_ "github.com/mobiledgex/edge-cloud/protogen"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Auto-generated code: DO NOT EDIT

// Request summary for ShowNode
// swagger:parameters ShowNode
type swaggerShowNode struct {
	// in: body
	Body RegionNode
}

type RegionNode struct {
	// required: true
	// Region name
	Region string
	Node   edgeproto.Node
}

func (s *RegionNode) GetRegion() string {
	return s.Region
}

func (s *RegionNode) GetObj() interface{} {
	return &s.Node
}

func (s *RegionNode) GetObjName() string {
	return "Node"
}
func (s *RegionNode) GetObjFields() []string {
	return s.Node.Fields
}

func (s *RegionNode) SetObjFields(fields []string) {
	s.Node.Fields = fields
}
