// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: operatorcode.proto

package ormapi

import (
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	edgeproto "github.com/mobiledgex/edge-cloud/edgeproto"
	_ "github.com/mobiledgex/edge-cloud/protogen"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Auto-generated code: DO NOT EDIT

// Request summary for CreateOperatorCode
// swagger:parameters CreateOperatorCode
type swaggerCreateOperatorCode struct {
	// in: body
	Body RegionOperatorCode
}

type RegionOperatorCode struct {
	// required: true
	// Region name
	Region       string
	OperatorCode edgeproto.OperatorCode
}

// Request summary for DeleteOperatorCode
// swagger:parameters DeleteOperatorCode
type swaggerDeleteOperatorCode struct {
	// in: body
	Body RegionOperatorCode
}

// Request summary for ShowOperatorCode
// swagger:parameters ShowOperatorCode
type swaggerShowOperatorCode struct {
	// in: body
	Body RegionOperatorCode
}
