// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: restagtable.proto

package ormapi

import edgeproto "github.com/mobiledgex/edge-cloud/edgeproto"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/googleapis/google/api"
import _ "github.com/mobiledgex/edge-cloud/protogen"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Auto-generated code: DO NOT EDIT

type RegionResTagTable struct {
	Region      string                `json:"region"`
	ResTagTable edgeproto.ResTagTable `json:"restagtable"`
}

type RegionResTagTableKey struct {
	Region         string                   `json:"region"`
	ResTagTableKey edgeproto.ResTagTableKey `json:"restagtablekey"`
}
