// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: trustpolicy.proto

package ormapi

import (
	fmt "fmt"
	edgeproto "github.com/edgexr/edge-cloud/edgeproto"
	_ "github.com/edgexr/edge-cloud/protogen"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Auto-generated code: DO NOT EDIT

// Request summary for CreateTrustPolicy
// swagger:parameters CreateTrustPolicy
type swaggerCreateTrustPolicy struct {
	// in: body
	Body RegionTrustPolicy
}

type RegionTrustPolicy struct {
	// Region name
	// required: true
	Region string
	// TrustPolicy in region
	TrustPolicy edgeproto.TrustPolicy
}

func (s *RegionTrustPolicy) GetRegion() string {
	return s.Region
}

func (s *RegionTrustPolicy) GetObj() interface{} {
	return &s.TrustPolicy
}

func (s *RegionTrustPolicy) GetObjName() string {
	return "TrustPolicy"
}
func (s *RegionTrustPolicy) GetObjFields() []string {
	return s.TrustPolicy.Fields
}

func (s *RegionTrustPolicy) SetObjFields(fields []string) {
	s.TrustPolicy.Fields = fields
}

// Request summary for DeleteTrustPolicy
// swagger:parameters DeleteTrustPolicy
type swaggerDeleteTrustPolicy struct {
	// in: body
	Body RegionTrustPolicy
}

// Request summary for UpdateTrustPolicy
// swagger:parameters UpdateTrustPolicy
type swaggerUpdateTrustPolicy struct {
	// in: body
	Body RegionTrustPolicy
}

// Request summary for ShowTrustPolicy
// swagger:parameters ShowTrustPolicy
type swaggerShowTrustPolicy struct {
	// in: body
	Body RegionTrustPolicy
}
