FROM ubuntu:18.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
	apt-transport-https \
        ca-certificates \
        curl \
	dirmngr \
	openssh-client \
	openssh-server \
	openssh-sftp-server \
	python \
	python2.7 \
	python3 \
        python-pip \
	software-properties-common \
	systemd \
	tzdata \
	unzip \
	vim \
	wget

# Turn off auto-upgrades
RUN sed -i 's/"1"/"0"/' /etc/apt/apt.conf.d/20auto-upgrades

RUN echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ bionic main" >/etc/apt/sources.list.d/azure-cli.list
RUN echo "deb http://packages.cloud.google.com/apt cloud-sdk-bionic main" >/etc/apt/sources.list.d/google-cloud-sdk.list
RUN curl -sL https://packages.microsoft.com/keys/microsoft.asc \
	| gpg --dearmor >/etc/apt/trusted.gpg.d/microsoft.asc.gpg
RUN curl -sL https://packages.cloud.google.com/apt/doc/apt-key.gpg \
	| apt-key add -
RUN echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" >/etc/apt/sources.list.d/kubernetes.list

RUN apt-get update && apt-get install -y \
	azure-cli=2.0.75-1~bionic \
	google-cloud-sdk=267.0.0-0 \
	kubectl=1.16.2-00 \
	qemu-utils=1:2.11+dfsg-1ubuntu7.29

COPY requirements.txt .
RUN pip install -r requirements.txt

## GOVC
RUN curl -sL https://github.com/vmware/govmomi/releases/download/v0.23.0/govc_linux_amd64.gz \
	| gunzip >/usr/local/bin/govc \
	&& chmod ug+rx /usr/local/bin/govc

## TERRAFORM
RUN curl -sL https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip >terraform.zip \
	&& unzip terraform.zip \
	&& mv terraform /usr/local/bin/ \
	&& rm -f terraform.zip

COPY edge-cloud-base-image.root/_ssh /root/.ssh
COPY edge-cloud-base-image.root/_mobiledgex /root/.mobiledgex
RUN chmod 400 /root/.mobiledgex/id_rsa_mex /root/.mobiledgex/id_rsa_mobiledgex
