FROM ubuntu:18.04

RUN apt-get update && apt-get install -y curl

RUN curl -sfLO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl \
	&& chmod +x kubectl \
	&& mv kubectl /usr/local/bin

COPY influxdb-backup /usr/local/bin
RUN chmod 555 /usr/local/bin/influxdb-backup
