name 'copy_third_party_notice'
maintainer 'MobiledgeX Inc.'
maintainer_email 'mobiledgex.ops@mobiledgex.com'
description 'Copy THIRD_PARTY_NOTICE.txt file to platform VMs'
version '1.0.0'
chef_version '>= 14.0'
