ANSIBLE_INVENTORY	= mexdemo

include ../Makefile

plan deploy:
	@echo
	@echo "=================================================================="
	@echo "Sorry! Terraform deployments not supported for mexdemo environment"
	@echo "=================================================================="
	@echo
