// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: appinst.proto

package ctrlclient

import (
	"context"
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	fedclient "github.com/mobiledgex/edge-cloud-infra/mc/federation/client"
	"github.com/mobiledgex/edge-cloud-infra/mc/ormutil"
	_ "github.com/mobiledgex/edge-cloud/d-match-engine/dme-proto"
	edgeproto "github.com/mobiledgex/edge-cloud/edgeproto"
	"github.com/mobiledgex/edge-cloud/log"
	_ "github.com/mobiledgex/edge-cloud/protogen"
	"io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Auto-generated code: DO NOT EDIT

func CreateAppInstStream(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.AppInst, connObj ClientConnMgr, cb func(res *edgeproto.Result) error) error {
	federationId, err := fedclient.GetFederationIDFromCloudlet(obj.Key.ClusterInstKey.CloudletKey.Name)
	if err != nil {
		return err
	}
	if federationId > 0 {
		fedClientObj, found, err := fedclient.GetFederationClient(ctx, rc.Database, federationId)
		if err != nil {
			return err
		}
		if found {
			var clientIntf interface{}
			clientIntf = fedClientObj
			clientApi, ok := clientIntf.(interface {
				CreateAppInstStream(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.AppInst, cb func(res *edgeproto.Result) error) error
			})
			if !ok {
				// method doesn't exist
				return fmt.Errorf("CreateAppInst is not implemented for federation partner")
			}
			return clientApi.CreateAppInstStream(ctx, rc, obj, cb)
		}
	}
	conn, err := connObj.GetRegionConn(ctx, rc.Region)
	if err != nil {
		return err
	}
	api := edgeproto.NewAppInstApiClient(conn)
	log.SpanLog(ctx, log.DebugLevelApi, "start controller api")
	defer log.SpanLog(ctx, log.DebugLevelApi, "finish controller api")
	stream, err := api.CreateAppInst(ctx, obj)
	if err != nil {
		return err
	}
	for {
		res, err := stream.Recv()
		if err == io.EOF {
			err = nil
			break
		}
		if err != nil {
			return err
		}
		err = cb(res)
		if err != nil {
			return err
		}
	}
	return nil
}

func DeleteAppInstStream(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.AppInst, connObj ClientConnMgr, cb func(res *edgeproto.Result) error) error {
	federationId, err := fedclient.GetFederationIDFromCloudlet(obj.Key.ClusterInstKey.CloudletKey.Name)
	if err != nil {
		return err
	}
	if federationId > 0 {
		fedClientObj, found, err := fedclient.GetFederationClient(ctx, rc.Database, federationId)
		if err != nil {
			return err
		}
		if found {
			var clientIntf interface{}
			clientIntf = fedClientObj
			clientApi, ok := clientIntf.(interface {
				DeleteAppInstStream(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.AppInst, cb func(res *edgeproto.Result) error) error
			})
			if !ok {
				// method doesn't exist
				return fmt.Errorf("DeleteAppInst is not implemented for federation partner")
			}
			return clientApi.DeleteAppInstStream(ctx, rc, obj, cb)
		}
	}
	conn, err := connObj.GetRegionConn(ctx, rc.Region)
	if err != nil {
		return err
	}
	api := edgeproto.NewAppInstApiClient(conn)
	log.SpanLog(ctx, log.DebugLevelApi, "start controller api")
	defer log.SpanLog(ctx, log.DebugLevelApi, "finish controller api")
	stream, err := api.DeleteAppInst(ctx, obj)
	if err != nil {
		return err
	}
	for {
		res, err := stream.Recv()
		if err == io.EOF {
			err = nil
			break
		}
		if err != nil {
			return err
		}
		err = cb(res)
		if err != nil {
			return err
		}
	}
	return nil
}

func RefreshAppInstStream(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.AppInst, connObj ClientConnMgr, cb func(res *edgeproto.Result) error) error {
	federationId, err := fedclient.GetFederationIDFromCloudlet(obj.Key.ClusterInstKey.CloudletKey.Name)
	if err != nil {
		return err
	}
	if federationId > 0 {
		fedClientObj, found, err := fedclient.GetFederationClient(ctx, rc.Database, federationId)
		if err != nil {
			return err
		}
		if found {
			var clientIntf interface{}
			clientIntf = fedClientObj
			clientApi, ok := clientIntf.(interface {
				RefreshAppInstStream(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.AppInst, cb func(res *edgeproto.Result) error) error
			})
			if !ok {
				// method doesn't exist
				return fmt.Errorf("RefreshAppInst is not implemented for federation partner")
			}
			return clientApi.RefreshAppInstStream(ctx, rc, obj, cb)
		}
	}
	conn, err := connObj.GetRegionConn(ctx, rc.Region)
	if err != nil {
		return err
	}
	api := edgeproto.NewAppInstApiClient(conn)
	log.SpanLog(ctx, log.DebugLevelApi, "start controller api")
	defer log.SpanLog(ctx, log.DebugLevelApi, "finish controller api")
	stream, err := api.RefreshAppInst(ctx, obj)
	if err != nil {
		return err
	}
	for {
		res, err := stream.Recv()
		if err == io.EOF {
			err = nil
			break
		}
		if err != nil {
			return err
		}
		err = cb(res)
		if err != nil {
			return err
		}
	}
	return nil
}

func UpdateAppInstStream(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.AppInst, connObj ClientConnMgr, cb func(res *edgeproto.Result) error) error {
	federationId, err := fedclient.GetFederationIDFromCloudlet(obj.Key.ClusterInstKey.CloudletKey.Name)
	if err != nil {
		return err
	}
	if federationId > 0 {
		fedClientObj, found, err := fedclient.GetFederationClient(ctx, rc.Database, federationId)
		if err != nil {
			return err
		}
		if found {
			var clientIntf interface{}
			clientIntf = fedClientObj
			clientApi, ok := clientIntf.(interface {
				UpdateAppInstStream(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.AppInst, cb func(res *edgeproto.Result) error) error
			})
			if !ok {
				// method doesn't exist
				return fmt.Errorf("UpdateAppInst is not implemented for federation partner")
			}
			return clientApi.UpdateAppInstStream(ctx, rc, obj, cb)
		}
	}
	conn, err := connObj.GetRegionConn(ctx, rc.Region)
	if err != nil {
		return err
	}
	api := edgeproto.NewAppInstApiClient(conn)
	log.SpanLog(ctx, log.DebugLevelApi, "start controller api")
	defer log.SpanLog(ctx, log.DebugLevelApi, "finish controller api")
	stream, err := api.UpdateAppInst(ctx, obj)
	if err != nil {
		return err
	}
	for {
		res, err := stream.Recv()
		if err == io.EOF {
			err = nil
			break
		}
		if err != nil {
			return err
		}
		err = cb(res)
		if err != nil {
			return err
		}
	}
	return nil
}

type ShowAppInstAuthz interface {
	Ok(obj *edgeproto.AppInst) (bool, bool)
	Filter(obj *edgeproto.AppInst)
}

func ShowAppInstStream(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.AppInst, connObj ClientConnMgr, authz ShowAppInstAuthz, cb func(res *edgeproto.AppInst) error) error {
	fedClients, err := fedclient.GetFederationClients(ctx, rc.Database, rc.Region, &obj.Key.ClusterInstKey.CloudletKey)
	if err != nil {
		return err
	}
	var clientIntf interface{}
	for _, fedClientObj := range fedClients {
		clientIntf = &fedClientObj
		clientApi, ok := clientIntf.(interface {
			ShowAppInstStream(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.AppInst, cb func(res *edgeproto.AppInst) error) error
		})
		if !ok {
			// method doesn't exist, ignore
			continue
		}

		err = clientApi.ShowAppInstStream(ctx, rc, obj, cb)
		if err != nil {
			return err
		}
	}
	conn, err := connObj.GetRegionConn(ctx, rc.Region)
	if err != nil {
		return err
	}
	api := edgeproto.NewAppInstApiClient(conn)
	log.SpanLog(ctx, log.DebugLevelApi, "start controller api")
	defer log.SpanLog(ctx, log.DebugLevelApi, "finish controller api")
	stream, err := api.ShowAppInst(ctx, obj)
	if err != nil {
		return err
	}
	for {
		res, err := stream.Recv()
		if err == io.EOF {
			err = nil
			break
		}
		if err != nil {
			return err
		}
		if !rc.SkipAuthz {
			if authz != nil {
				authzOk, filterOutput := authz.Ok(res)
				if !authzOk {
					continue
				}
				if filterOutput {
					authz.Filter(res)
				}
			}
		}
		err = cb(res)
		if err != nil {
			return err
		}
	}
	return nil
}

func RequestAppInstLatencyObj(ctx context.Context, rc *ormutil.RegionContext, obj *edgeproto.AppInstLatency, connObj ClientConnMgr) (*edgeproto.Result, error) {
	conn, err := connObj.GetRegionConn(ctx, rc.Region)
	if err != nil {
		return nil, err
	}
	api := edgeproto.NewAppInstLatencyApiClient(conn)
	log.SpanLog(ctx, log.DebugLevelApi, "start controller api")
	defer log.SpanLog(ctx, log.DebugLevelApi, "finish controller api")
	return api.RequestAppInstLatency(ctx, obj)
}
