name 'copy_resource_tracker'
maintainer 'MobiledgeX Inc.'
maintainer_email 'mobiledgex.ops@mobiledgex.com'
description 'Copy resource-tracker binary to docker app VMs'
version '1.0.1'
chef_version '>= 14.0'
