pipeline {
    options {
        skipDefaultCheckout true
        timeout(time: 60, unit: 'MINUTES')
    }
    agent { label 'cicd' }
    stages {
        stage('Checkout') {
            steps {
                dir(path: 'go/src/github.com/mobiledgex/edge-cloud-infra') {
                    checkout scm
                }
                dir(path: 'go/src/github.com/mobiledgex/edge-cloud') {
                    git url: 'git@github.com:mobiledgex/edge-cloud.git'
                }
                dir(path: 'go/src/github.com/mobiledgex/edge-proto') {
                    git url: 'git@github.com:mobiledgex/edge-proto.git'
                }
            }
        }
        stage('Edge-Cloud Version') {
            steps {
                dir(path: 'go/src/github.com/mobiledgex/edge-cloud-infra') {
                    sh label: 'make edge-cloud-version-set', script: '''$!/bin/bash
export PATH=$PATH:$WORKSPACE/go/bin:$HOME/go/bin
export GOPATH=$WORKSPACE/go
make edge-cloud-version-set
                    '''
                }
            }
        }
        stage('Clean') {
            steps {
                dir(path: 'go/src/github.com/mobiledgex/edge-cloud') {
                    sh label: 'make clean', script: '''#!/bin/bash
export PATH=$PATH:$WORKSPACE/go/bin:$HOME/go/bin
export GOPATH=$WORKSPACE/go
make clean
                    '''
                }
                dir(path: 'go/src/github.com/mobiledgex/edge-cloud') {
                    sh label: 'git clean edge-cloud', script: 'git clean -f -d -x'
                }
                dir(path: 'go/src/github.com/mobiledgex/edge-cloud-infra') {
                    sh label: 'git clean edge-cloud-infra', script: 'git clean -f -d -x'
                }
            }
        }
        stage('Pre-requisites') {
            steps {
                dir(path: 'go/src/github.com/grpc-ecosystem') {
                    sh label: 'git clone grpc-gateway', script: 'git clone https://github.com/mobiledgex/grpc-gateway.git'
                }
                dir(path: 'go/src/github.com/mobiledgex/edge-cloud') {
                    sh label: 'go mod download', script: '''#!/bin/bash
export PATH=$PATH:$WORKSPACE/go/bin:$HOME/go/bin
export GOPATH=$WORKSPACE/go
export GO111MODULE=on
go mod download
                    '''
                }
                dir(path: 'go/src/github.com/mobiledgex/edge-cloud') {
                    sh label: 'make tools', script: '''#!/bin/bash
export PATH=$PATH:$WORKSPACE/go/bin:$HOME/go/bin
export GOPATH=$WORKSPACE/go
make tools
                    '''
                }
            }
        }
        stage('Build') {
            steps {
                dir(path: 'go/src/github.com/mobiledgex/edge-cloud-infra') {
                    sh label: 'make', script: '''#!/bin/bash
export PATH=$PATH:$WORKSPACE/go/bin:$HOME/go/bin
export GOPATH=$WORKSPACE/go
make
                    '''
                }
            }
        }
        stage('Test') {
            options {
                timeout(time: 40, unit: 'MINUTES')
            }
            steps {
                lock('testbed') {
                    retry(2) {
                        sleep 10
                        dir(path: 'go/src/github.com/mobiledgex/edge-cloud-infra') {
                            sh label: 'unit tests', script: '''#!/bin/bash
export PATH=$PATH:$WORKSPACE/go/bin:$HOME/go/bin:/usr/lib/postgresql/10/bin
export GOPATH=$WORKSPACE/go
export GO111MODULE=on
UNIT_TEST_LOG=/tmp/edge-cloud-infra-unit-test.${BUILD_TAG}.log make unit-test
                            '''
                        }
                    }
                }
            }
        }
        stage('Notify') {
            when {
                changeRequest()
                beforeAgent true
            }
            steps {
                slackSend color: 'good',
                          channel: '#ci-cd',
                          message: "<${env.CHANGE_URL}|Infra Pull request PR-${env.CHANGE_ID}> ready for review: (${env.CHANGE_AUTHOR} \"${env.CHANGE_TITLE}\")"
            }
        }
    }
    post {
        success {
            slackSend color: 'good', message: "Build Successful - ${env.JOB_NAME} #${env.BUILD_NUMBER} (<${env.RUN_DISPLAY_URL}|Open>)"
        }
        failure {
            slackSend color: 'warning', message: "Build Failed - ${env.JOB_NAME} #${env.BUILD_NUMBER} (<${env.RUN_DISPLAY_URL}|Open>)"
        }
    }
}
