#!/bin/bash
PATH='/usr/bin:/bin:/usr/local/bin'; export PATH

USAGE="usage: $( basename $0 ) <command>

  add <user>  Add Telefonica user account
  ls          List Telefonica user accounts
  rm <user>   Remove Telefonica user account
"

add_user() {
    username="$1"
    if [[ -z "$username" ]]; then
        echo "usage: $( basename $0 ) $COMM <user>" >&2
        exit 1
    fi
    tctl users add "$1" --roles=telefonica
}

ls_users() {
    # Print header and lines with "telefonica" in the roles column
    tctl users ls | awk 'NR < 3 || $2 ~ "telefonica"'
}

rm_user() {
    username="$1"
    if [[ -z "$username" ]]; then
        echo "usage: $( basename $0 ) $COMM <user>" >&2
        exit 1
    fi

    # Match username with "telefonica" in the roles column
    tefuser=$( tctl users ls | awk -v tefuser="$username" '$1 == tefuser && $2 ~ "telefonica" {print $1}' )
    if [[ "$username" != "$tefuser" ]]; then
        echo "error: user not found: $username" >&2
        exit 2
    fi

    tctl users rm "$username"
}

COMM="$1"; shift
case "$COMM" in
    add|create)         add_user "$1" ;;
    rm|remove|delete)   rm_user "$1" ;;
    ls|list)            ls_users ;;
    *)                  echo "$USAGE" >&2; exit 1 ;;
esac
