name 'upgrade_mobiledgex_package'
maintainer 'MobiledgeX Inc.'
maintainer_email 'mobiledgex.ops@mobiledgex.com'
description 'Upgrade mobiledgex apt package on rootLb VMs'
version '1.0.8'
chef_version '>= 14.0'
