// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: clusterinst.proto

package orm

import edgeproto "github.com/mobiledgex/edge-cloud/edgeproto"
import "github.com/labstack/echo"
import "net/http"
import "context"
import "io"
import "encoding/json"
import "strings"
import "github.com/mobiledgex/edge-cloud/log"
import "github.com/mobiledgex/edge-cloud-infra/mc/ormapi"
import "google.golang.org/grpc/status"
import "github.com/gorilla/websocket"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/googleapis/google/api"
import _ "github.com/mobiledgex/edge-cloud/protogen"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Auto-generated code: DO NOT EDIT

func CreateClusterInst(c echo.Context) error {
	ctx := GetContext(c)
	rc := &RegionContext{}
	var err error
	var ws *websocket.Conn
	if strings.HasPrefix(c.Request().URL.Path, "/ws") {
		ws, err = websocketConnect(c)
		if err != nil {
			return err
		}
		if ws == nil {
			return nil
		}
		defer ws.Close()
	}

	claims, err := getClaims(c)
	if err != nil {
		return err
	}
	rc.username = claims.Username

	in := ormapi.RegionClusterInst{}
	if ws == nil {
		if err := c.Bind(&in); err != nil {
			return c.JSON(http.StatusBadRequest, Msg("Invalid POST data"))
		}
	} else {
		err = ws.ReadJSON(&in)
		if err != nil {
			if err == io.EOF || err == io.ErrUnexpectedEOF {
				return setReply(c, ws, fmt.Errorf("Invalid data"), nil)
			}
			return setReply(c, ws, err, nil)
		}
	}
	rc.region = in.Region
	span := log.SpanFromContext(ctx)
	span.SetTag("org", in.ClusterInst.Key.Developer)

	// stream func may return "forbidden", so don't write
	// header until we know it's ok
	wroteHeader := false
	err = CreateClusterInstStream(ctx, rc, &in.ClusterInst, func(res *edgeproto.Result) {
		payload := ormapi.StreamPayload{}
		payload.Data = res
		if ws != nil {
			err = ws.WriteJSON(payload)
		} else {
			if !wroteHeader {
				c.Response().Header().Set(echo.HeaderContentType, echo.MIMEApplicationJSON)
				c.Response().WriteHeader(http.StatusOK)
				wroteHeader = true
			}
			json.NewEncoder(c.Response()).Encode(payload)
			c.Response().Flush()
		}
	})
	if err != nil {
		if st, ok := status.FromError(err); ok {
			err = fmt.Errorf("%s", st.Message())
		}
		if !wroteHeader {
			return setReply(c, ws, err, nil)
		}
		res := ormapi.Result{}
		res.Message = err.Error()
		res.Code = http.StatusBadRequest
		payload := ormapi.StreamPayload{Result: &res}
		if ws != nil {
			ws.WriteJSON(payload)
		} else {
			json.NewEncoder(c.Response()).Encode(payload)
		}
	}
	return nil
}

func CreateClusterInstStream(ctx context.Context, rc *RegionContext, obj *edgeproto.ClusterInst, cb func(res *edgeproto.Result)) error {
	if !rc.skipAuthz {
		if err := authzCreateClusterInst(ctx, rc.region, rc.username, obj,
			ResourceClusterInsts, ActionManage); err != nil {
			return err
		}
	}
	if rc.conn == nil {
		conn, err := connectController(ctx, rc.region)
		if err != nil {
			return err
		}
		rc.conn = conn
		defer func() {
			rc.conn.Close()
			rc.conn = nil
		}()
	}
	api := edgeproto.NewClusterInstApiClient(rc.conn)
	stream, err := api.CreateClusterInst(ctx, obj)
	if err != nil {
		return err
	}
	for {
		res, err := stream.Recv()
		if err == io.EOF {
			err = nil
			break
		}
		if err != nil {
			return err
		}
		cb(res)
	}
	return nil
}

func CreateClusterInstObj(ctx context.Context, rc *RegionContext, obj *edgeproto.ClusterInst) ([]edgeproto.Result, error) {
	arr := []edgeproto.Result{}
	err := CreateClusterInstStream(ctx, rc, obj, func(res *edgeproto.Result) {
		arr = append(arr, *res)
	})
	return arr, err
}

func DeleteClusterInst(c echo.Context) error {
	ctx := GetContext(c)
	rc := &RegionContext{}
	var err error
	var ws *websocket.Conn
	if strings.HasPrefix(c.Request().URL.Path, "/ws") {
		ws, err = websocketConnect(c)
		if err != nil {
			return err
		}
		if ws == nil {
			return nil
		}
		defer ws.Close()
	}

	claims, err := getClaims(c)
	if err != nil {
		return err
	}
	rc.username = claims.Username

	in := ormapi.RegionClusterInst{}
	if ws == nil {
		if err := c.Bind(&in); err != nil {
			return c.JSON(http.StatusBadRequest, Msg("Invalid POST data"))
		}
	} else {
		err = ws.ReadJSON(&in)
		if err != nil {
			if err == io.EOF || err == io.ErrUnexpectedEOF {
				return setReply(c, ws, fmt.Errorf("Invalid data"), nil)
			}
			return setReply(c, ws, err, nil)
		}
	}
	rc.region = in.Region
	span := log.SpanFromContext(ctx)
	span.SetTag("org", in.ClusterInst.Key.Developer)

	// stream func may return "forbidden", so don't write
	// header until we know it's ok
	wroteHeader := false
	err = DeleteClusterInstStream(ctx, rc, &in.ClusterInst, func(res *edgeproto.Result) {
		payload := ormapi.StreamPayload{}
		payload.Data = res
		if ws != nil {
			err = ws.WriteJSON(payload)
		} else {
			if !wroteHeader {
				c.Response().Header().Set(echo.HeaderContentType, echo.MIMEApplicationJSON)
				c.Response().WriteHeader(http.StatusOK)
				wroteHeader = true
			}
			json.NewEncoder(c.Response()).Encode(payload)
			c.Response().Flush()
		}
	})
	if err != nil {
		if st, ok := status.FromError(err); ok {
			err = fmt.Errorf("%s", st.Message())
		}
		if !wroteHeader {
			return setReply(c, ws, err, nil)
		}
		res := ormapi.Result{}
		res.Message = err.Error()
		res.Code = http.StatusBadRequest
		payload := ormapi.StreamPayload{Result: &res}
		if ws != nil {
			ws.WriteJSON(payload)
		} else {
			json.NewEncoder(c.Response()).Encode(payload)
		}
	}
	return nil
}

func DeleteClusterInstStream(ctx context.Context, rc *RegionContext, obj *edgeproto.ClusterInst, cb func(res *edgeproto.Result)) error {
	if !rc.skipAuthz && !authorized(ctx, rc.username, obj.Key.Developer,
		ResourceClusterInsts, ActionManage) {
		return echo.ErrForbidden
	}
	if rc.conn == nil {
		conn, err := connectController(ctx, rc.region)
		if err != nil {
			return err
		}
		rc.conn = conn
		defer func() {
			rc.conn.Close()
			rc.conn = nil
		}()
	}
	api := edgeproto.NewClusterInstApiClient(rc.conn)
	stream, err := api.DeleteClusterInst(ctx, obj)
	if err != nil {
		return err
	}
	for {
		res, err := stream.Recv()
		if err == io.EOF {
			err = nil
			break
		}
		if err != nil {
			return err
		}
		cb(res)
	}
	return nil
}

func DeleteClusterInstObj(ctx context.Context, rc *RegionContext, obj *edgeproto.ClusterInst) ([]edgeproto.Result, error) {
	arr := []edgeproto.Result{}
	err := DeleteClusterInstStream(ctx, rc, obj, func(res *edgeproto.Result) {
		arr = append(arr, *res)
	})
	return arr, err
}

func UpdateClusterInst(c echo.Context) error {
	ctx := GetContext(c)
	rc := &RegionContext{}
	var err error
	var ws *websocket.Conn
	if strings.HasPrefix(c.Request().URL.Path, "/ws") {
		ws, err = websocketConnect(c)
		if err != nil {
			return err
		}
		if ws == nil {
			return nil
		}
		defer ws.Close()
	}

	claims, err := getClaims(c)
	if err != nil {
		return err
	}
	rc.username = claims.Username

	in := ormapi.RegionClusterInst{}
	if ws == nil {
		if err := c.Bind(&in); err != nil {
			return c.JSON(http.StatusBadRequest, Msg("Invalid POST data"))
		}
	} else {
		err = ws.ReadJSON(&in)
		if err != nil {
			if err == io.EOF || err == io.ErrUnexpectedEOF {
				return setReply(c, ws, fmt.Errorf("Invalid data"), nil)
			}
			return setReply(c, ws, err, nil)
		}
	}
	rc.region = in.Region
	span := log.SpanFromContext(ctx)
	span.SetTag("org", in.ClusterInst.Key.Developer)

	// stream func may return "forbidden", so don't write
	// header until we know it's ok
	wroteHeader := false
	err = UpdateClusterInstStream(ctx, rc, &in.ClusterInst, func(res *edgeproto.Result) {
		payload := ormapi.StreamPayload{}
		payload.Data = res
		if ws != nil {
			err = ws.WriteJSON(payload)
		} else {
			if !wroteHeader {
				c.Response().Header().Set(echo.HeaderContentType, echo.MIMEApplicationJSON)
				c.Response().WriteHeader(http.StatusOK)
				wroteHeader = true
			}
			json.NewEncoder(c.Response()).Encode(payload)
			c.Response().Flush()
		}
	})
	if err != nil {
		if st, ok := status.FromError(err); ok {
			err = fmt.Errorf("%s", st.Message())
		}
		if !wroteHeader {
			return setReply(c, ws, err, nil)
		}
		res := ormapi.Result{}
		res.Message = err.Error()
		res.Code = http.StatusBadRequest
		payload := ormapi.StreamPayload{Result: &res}
		if ws != nil {
			ws.WriteJSON(payload)
		} else {
			json.NewEncoder(c.Response()).Encode(payload)
		}
	}
	return nil
}

func UpdateClusterInstStream(ctx context.Context, rc *RegionContext, obj *edgeproto.ClusterInst, cb func(res *edgeproto.Result)) error {
	if !rc.skipAuthz && !authorized(ctx, rc.username, obj.Key.Developer,
		ResourceClusterInsts, ActionManage) {
		return echo.ErrForbidden
	}
	if rc.conn == nil {
		conn, err := connectController(ctx, rc.region)
		if err != nil {
			return err
		}
		rc.conn = conn
		defer func() {
			rc.conn.Close()
			rc.conn = nil
		}()
	}
	api := edgeproto.NewClusterInstApiClient(rc.conn)
	stream, err := api.UpdateClusterInst(ctx, obj)
	if err != nil {
		return err
	}
	for {
		res, err := stream.Recv()
		if err == io.EOF {
			err = nil
			break
		}
		if err != nil {
			return err
		}
		cb(res)
	}
	return nil
}

func UpdateClusterInstObj(ctx context.Context, rc *RegionContext, obj *edgeproto.ClusterInst) ([]edgeproto.Result, error) {
	arr := []edgeproto.Result{}
	err := UpdateClusterInstStream(ctx, rc, obj, func(res *edgeproto.Result) {
		arr = append(arr, *res)
	})
	return arr, err
}

func ShowClusterInst(c echo.Context) error {
	ctx := GetContext(c)
	rc := &RegionContext{}
	var err error
	var ws *websocket.Conn
	if strings.HasPrefix(c.Request().URL.Path, "/ws") {
		ws, err = websocketConnect(c)
		if err != nil {
			return err
		}
		if ws == nil {
			return nil
		}
		defer ws.Close()
	}

	claims, err := getClaims(c)
	if err != nil {
		return err
	}
	rc.username = claims.Username

	in := ormapi.RegionClusterInst{}
	if ws == nil {
		if err := c.Bind(&in); err != nil {
			return c.JSON(http.StatusBadRequest, Msg("Invalid POST data"))
		}
	} else {
		err = ws.ReadJSON(&in)
		if err != nil {
			if err == io.EOF || err == io.ErrUnexpectedEOF {
				return setReply(c, ws, fmt.Errorf("Invalid data"), nil)
			}
			return setReply(c, ws, err, nil)
		}
	}
	rc.region = in.Region
	span := log.SpanFromContext(ctx)
	span.SetTag("org", in.ClusterInst.Key.Developer)

	// stream func may return "forbidden", so don't write
	// header until we know it's ok
	wroteHeader := false
	err = ShowClusterInstStream(ctx, rc, &in.ClusterInst, func(res *edgeproto.ClusterInst) {
		payload := ormapi.StreamPayload{}
		payload.Data = res
		if ws != nil {
			err = ws.WriteJSON(payload)
		} else {
			if !wroteHeader {
				c.Response().Header().Set(echo.HeaderContentType, echo.MIMEApplicationJSON)
				c.Response().WriteHeader(http.StatusOK)
				wroteHeader = true
			}
			json.NewEncoder(c.Response()).Encode(payload)
			c.Response().Flush()
		}
	})
	if err != nil {
		if st, ok := status.FromError(err); ok {
			err = fmt.Errorf("%s", st.Message())
		}
		if !wroteHeader {
			return setReply(c, ws, err, nil)
		}
		res := ormapi.Result{}
		res.Message = err.Error()
		res.Code = http.StatusBadRequest
		payload := ormapi.StreamPayload{Result: &res}
		if ws != nil {
			ws.WriteJSON(payload)
		} else {
			json.NewEncoder(c.Response()).Encode(payload)
		}
	}
	return nil
}

func ShowClusterInstStream(ctx context.Context, rc *RegionContext, obj *edgeproto.ClusterInst, cb func(res *edgeproto.ClusterInst)) error {
	var authz *ShowAuthz
	var err error
	if !rc.skipAuthz {
		authz, err = NewShowAuthz(ctx, rc.region, rc.username, ResourceClusterInsts, ActionView)
		if err == echo.ErrForbidden {
			return nil
		}
		if err != nil {
			return err
		}
	}
	if rc.conn == nil {
		conn, err := connectController(ctx, rc.region)
		if err != nil {
			return err
		}
		rc.conn = conn
		defer func() {
			rc.conn.Close()
			rc.conn = nil
		}()
	}
	api := edgeproto.NewClusterInstApiClient(rc.conn)
	stream, err := api.ShowClusterInst(ctx, obj)
	if err != nil {
		return err
	}
	for {
		res, err := stream.Recv()
		if err == io.EOF {
			err = nil
			break
		}
		if err != nil {
			return err
		}
		if !rc.skipAuthz {
			if !authz.Ok(res.Key.Developer) {
				continue
			}
		}
		cb(res)
	}
	return nil
}

func ShowClusterInstObj(ctx context.Context, rc *RegionContext, obj *edgeproto.ClusterInst) ([]edgeproto.ClusterInst, error) {
	arr := []edgeproto.ClusterInst{}
	err := ShowClusterInstStream(ctx, rc, obj, func(res *edgeproto.ClusterInst) {
		arr = append(arr, *res)
	})
	return arr, err
}
