name 'setup_services_anthos'
maintainer 'MobiledgeX Inc.'
maintainer_email 'mobiledgex.ops@mobiledgex.com'
description 'Setup services on docker/k8s containers anthos'
version '1.6.0'
chef_version '>= 14.0'
depends 'docker'
