#!/bin/bash 

if  [ $# -ne 1 ]
then
   echo "first argument to the script should be name of the vm to be stopped."
   exit 1
fi
vm=$1



status=`gcloud compute instances list --filter="name=($vm)" --format "value(status)"`

if [ "$status" != "TERMINATED" ]
then
      gcloud compute instances stop $vm --async
fi
